# Generated by Django 5.1 on 2024-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('matricula', models.DateField()),
                ('rut', models.IntegerField()),
                ('contraseña', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'appproject_estudiante',
                'managed': False,
            },
        ),
    ]
