# Generated by Django 5.1 on 2024-10-12 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('idClases', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_matricula', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('matricula', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=45)),
                ('clases', models.ManyToManyField(to='appproject.clases')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('no_presente', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.estudiante')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.clases')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appproject.curso')),
            ],
        ),
        migrations.AddField(
            model_name='clases',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.profesor'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fecha_registro', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.estudiante')),
                ('clase', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='appproject.clases')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.profesor')),
            ],
        ),
    ]
